#!/usr/bin/env bash
#
# Exports
export BASH_SILENCE_DEPRECATION_WARNING=1

## Brew stuff
export HOMEBREW_NO_AUTO_UPDATE=1      # `brew update` done with a cronjob, because this is slow
export PATH="/opt/homebrew/bin:$PATH" # Default install of brew executables such as `aws` and `ggrep`
# Override BSD utilities with GNU alternatives
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/opt/findutils/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/opt/curl/bin:$PATH"
export MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:$PATH"
export MANPATH="/opt/homebrew/opt/grep/libexec/gnuman:$MANPATH"
export MANPATH="/opt/homebrew/opt/gnu-sed/libexec/gnuman:$MANPATH"
export MANPATH="/opt/homebrew/opt/findutils/libexec/gnuman:$MANPATH"

# Bash Completion
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

# FZF stuff
eval "$(fzf --bash)"

## MacOS Dev Tools
source /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash
source /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh

## ----------- FOR COMPILING CODE ONLY !! ------------ ##
## this may be required when installing from brew also. Only enable
## this suff when you need it.

## 1. OPENSSL - brew version
#export PATH="/usr/local/opt/openssl/bin:$PATH"
## Build Flags
#export LDFLAGS=-L/usr/local/opt/openssl/lib
#export CPPFLAGS=-I/usr/local/opt/openssl/include
#export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

## ----------- END TEMP COMPILATION STUFF  ------------ ##
#

# https://github.com/sharkdp/vivid/releases
export LS_COLORS=$(vivid generate solarized-dark)

# Manual conda init
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.bash' 'hook' 2>/dev/null)"
if [ $? -eq 0 ]; then
	eval "$__conda_setup"
else
	if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
		. "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
	else
		export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
	fi
fi
unset __conda_setup
# <<< conda initialize <<<

conda activate general
